captainVersion: 4
services:
  '$$cap_appname':
    image: ghcr.io/linuxserver/healthchecks
    container_name: healthchecks
    environment:
      PUID: '$$cap_PUID'
      PGID: '$$cap_PGID'
      SITE_ROOT: '$$cap_SITE_ROOT'
      SITE_NAME: '$$cap_SITE_NAME'
      DEFAULT_FROM_EMAIL: '$$cap_DEFAULT_FROM_EMAIL'
      EMAIL_HOST: '$$cap_EMAIL_HOST'
      EMAIL_PORT: '$$cap_EMAIL_PORT'
      EMAIL_HOST_USER: '$$cap_EMAIL_HOST_USER'
      EMAIL_HOST_PASSWORD: '$$cap_EMAIL_HOST_PASSWORD'
      EMAIL_USE_TLS: '$$cap_EMAIL_USE_TLS'
      ALLOWED_HOSTS: '$$cap_ALLOWED_HOSTS'
      SUPERUSER_EMAIL: '$$cap_SUPERUSER_EMAIL'
      SUPERUSER_PASSWORD: '$$cap_SUPERUSER_PASSWORD'
    volumes:
      - $$cap_appname-healthchecks:/config
    ports:
      - 8000:8000
    restart: unless-stopped

caproverOneClickApp:
  variables:
    - id: '$$cap_myapp_version'
      label: HealthChecks
      defaultValue: '1.2.3'
      description: Check out their Docker page for the valid tags https://hub.docker.com/r/....../tags
      validRegex: "/.{1,}/"
  instructions:
    start: |-
      Simple and Effective Cron Job Monitoring
      We notify you when your nightly backups, weekly reports, cron jobs and scheduled tasks don't run on time.
    end:
  displayName: Health Checks
  isOfficial: false
  description: Simple and Effective Cron Job Monitoring
  documentation: Please Check https://healthchecks.io/docs/ For More Information