name: Validate One Click Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci && npm run validate_apps && npm run formatter
        env:
          GITHUB_PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
